name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - name: Install dependencies
      run: |
        bundle install

    - name: Run RSpec
      run: |
        bundle exec rspec

    - name: Run RuboCop
      run: |
        bundle exec rubocop

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2

    # Fly.io CLIのインストール
    - name: Install Fly.io CLI
      run: |
        curl -L https://fly.io/install.sh | sh

    # Fly.ioへのログイン（トークンはGitHub Secretsに保存）
    - name: Login to Fly.io
      run: flyctl auth token ${{ secrets.FLY_API_TOKEN }}

    # Fly.ioへのデプロイ
    - name: Deploy to Fly.io
      run: flyctl deploy
